site_name: Rico

theme:
  name: cinder
  site_favicon: docs/img/icon-rico.png
nav:
  - Home: index.md
  - Pré-Rastrabilidade: pre_rastre.md
  - Elicitação:
    - Requisitos: elicitacao/requisitos.md
    - Priorização: elicitacao/priorizacao.md
  - Disciplina: disciplina/disciplina.md
  - Entregas: entregas/entregas.md
  - Sprints: sprints/sprints.md

dev_addr: '0.0.0.0:8000'
