site_name: Rico

theme:
  name: 'material'
  site_favicon: docs/img/icon-rico.png
  feature:
    tabs: true
  palette:
    primary: '#211241'
    accent: 'black'
  language: 'pt'

dev_addr: '0.0.0.0:8000'
